global:
  postgresql:
    auth:
      postgresPassword: "SuperSecretPGAdminPa55word!"
      username: "test"
      password: "insecurePassword"
      database: "graphengine"
primary:
  initdb:
    scripts:
      init.sql: | 
        CREATE USER ory with PASSWORD "orypassword";
        CREATE DATABASE ory;
        GRANT ALL PRIVILEGES ON DATABASE ory TO ory;
