// This file is auto-generated by @hey-api/openapi-ts

export const $CreatedGraph = {
    description: 'The created graph',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id'],
    type: 'object',
    additionalProperties: false
} as const;

export const $GraphCreationParams = {
    properties: {
        graph: {
            type: 'string',
            description: 'The json serialized graph'
        },
        name: {
            type: 'string',
            description: 'A human readable name for the graph'
        }
    },
    required: ['graph', 'name'],
    type: 'object'
} as const;