// This file is auto-generated by @hey-api/openapi-ts

/**
 * The created graph
 */
export type CreatedGraph = {
    id: string;
};

export type GraphCreationParams = {
    /**
     * The json serialized graph
     */
    graph: string;
    /**
     * A human readable name for the graph
     */
    name: string;
};

export type $OpenApiTs = {
    '/graph': {
        post: {
            req: {
                requestBody: GraphCreationParams;
            };
            res: {
                201: CreatedGraph;
            };
        };
    };
    '/graph/{graphId}': {
        get: {
            req: {
                graphId: string;
            };
            res: {
                200: {
                    updatedAt: string;
                    createdAt: string;
                    owner: string;
                    graph: string;
                    name: string;
                    id: string;
                };
                /**
                 * Graph not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: {
                graphId: string;
            };
            res: {
                200: unknown;
                /**
                 * Graph not found
                 */
                404: unknown;
            };
        };
    };
};