// This file is auto-generated by @hey-api/openapi-ts

/**
 * The created graph
 */
export type CreatedGraph = {
    id: string;
};

export type GraphCreationParams = {
    /**
     * The json serialized graph
     */
    graph: string;
    /**
     * A human readable name for the graph
     */
    name: string;
};

export type Graph = {
    updatedAt: string;
    createdAt: string;
    owner: string;
    graph: string;
    name: string;
    id: string;
};

export type ListGraphParams = {
    perPage?: number;
    page?: number;
};

export type SchemaObject = {
    id?: string;
    $id?: string;
    $schema?: string;
    $async?: boolean;
    [key: string]: (unknown) | undefined;
};

export type GraphSchema = SchemaObject;

export type InvokeableInputDefinition = {
    type?: SchemaObject;
    value: unknown;
};

/**
 * Construct a type with a set of properties K of type T
 */
export type Record_string_InvokeableInputDefinition_ = {
    [key: string]: InvokeableInputDefinition;
};

export type InvokeParams = {
    graphId: string;
    payload: Record_string_InvokeableInputDefinition_;
};

export type PaginatedParams = {
    perPage?: number;
    page?: number;
};

export type CredentialCreationParams = unknown;

export type PaginatedListCredsParams = {
    perPage?: number;
    page?: number;
};

export type $OpenApiTs = {
    '/graph': {
        post: {
            req: {
                requestBody: GraphCreationParams;
            };
            res: {
                201: CreatedGraph;
            };
        };
        get: {
            req: {
                page?: number;
                perPage?: number;
            };
            res: {
                200: Array<Graph>;
            };
        };
    };
    '/graph/{graphId}': {
        get: {
            req: {
                graphId: string;
            };
            res: {
                200: Graph;
                /**
                 * Graph not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: {
                graphId: string;
            };
            res: {
                200: unknown;
                /**
                 * Graph not found
                 */
                404: unknown;
            };
        };
    };
    '/executions': {
        post: {
            req: {
                requestBody: InvokeParams;
            };
            res: {
                /**
                 * No content
                 */
                204: void;
            };
        };
        get: {
            req: {
                page?: number;
                perPage?: number;
            };
            res: {
                200: unknown;
            };
        };
    };
    '/executions/{id}': {
        get: {
            req: {
                id: string;
            };
            res: {
                200: unknown;
            };
        };
    };
    '/executions/{id}/artifacts/{artifactId}': {
        get: {
            req: {
                artifactId: string;
                id: string;
            };
            res: {
                /**
                 * No content
                 */
                204: void;
            };
        };
    };
    '/executions/{id}/logs/{artifactId}': {
        get: {
            req: {
                artifactId: string;
                id: string;
            };
            res: {
                /**
                 * No content
                 */
                204: void;
            };
        };
    };
    '/credentials': {
        post: {
            req: {
                requestBody: CredentialCreationParams;
            };
            res: {
                /**
                 * No content
                 */
                204: void;
            };
        };
        get: {
            req: {
                page?: number;
                perPage?: number;
            };
            res: {
                200: unknown;
            };
        };
    };
    '/credentials/{id}': {
        get: {
            req: {
                id: string;
            };
            res: {
                200: unknown;
            };
        };
        delete: {
            req: {
                id: string;
            };
            res: {
                200: unknown;
                /**
                 * Credential not found
                 */
                404: unknown;
            };
        };
    };
};