version: '3.7'

volumes:
  kratos-sqlite:
services:
  keto:
    image: oryd/keto:v0.11.1
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - ./data/keto:/home/ory
      
  kratos-migrate:
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./data/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos-admin:
    image: ghcr.io/dfoxg/kratos-admin-ui:2.3.1
    ports:
      - '4444:8080'
    restart: unless-stopped
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    ports:
      - "4455:4455"
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:7979/.ory/kratos/public/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4455
      - SECURITY_MODE=
  kratos:
    depends_on:
      - kratos-migrate
      # - jaeger
    image: oryd/kratos:v1.1.0
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: unless-stopped
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      # - TRACING_PROVIDER=jaeger
      # - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      # - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - KRATOS_SELF_URL=http://127.0.0.1:4433
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      # Must be >= 16 characters
      - SECRETS_DEFAULT=secretsecretsecretsecret
    volumes:
      -  type: volume
         source: kratos-sqlite
         target: /var/lib/sqlite
         read_only: false
      - ./data/kratos:/etc/config/kratos
  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    ports:
      - 7979:4455 # Reverse proxy
      - 7878:4456 # Decision API
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./data/oathkeeper:/etc/config/oathkeeper
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'