version: "3"

services:
  backend:
    image: graph-engine-backend
    container_name: backend
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    restart: always
    ports:
      - 5000:5000

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
    restart: always
    ports:
      - 3000:3000
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./packages/documentation/Dockerfile
    restart: always
    ports:
      - 4000:3000
