apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: graph-engine
deploy:
  helm:
    releases:
      - name: mailslurper
        chartPath: k8s/charts/mailslurper
        namespace: graph-engine
        createNamespace: true

      - name: database
        remoteChart: postgresql 
        version:  "15.2.5"
        repo: https://charts.bitnami.com/bitnami
        namespace: graph-engine
        valuesFiles:
          - "k8s/values/postgresql/values.yaml"
      - name: kratos
        repo: https://k8s.ory.sh/helm/charts
        namespace: graph-engine
        remoteChart: kratos
        version: "0.41.0"
        valuesFiles:
          - "k8s/values/kratos/values.yaml"