import { RegisterRoutes } from "@/routes/routes.ts"; // Import the 'routes' file generated by tsoa
import { NextApiRequest, NextApiResponse } from "next";

/** Function signature for route callbacks */
type FN = (request: any, response: any, next: any) => void;

/** Map from method to path to the route handling callbacks */
const methodToPathToFns: { readonly [method: string]: { [path: string]: readonly FN[] } } = {
    get: {},
    post: {},
    put:{},
    delete:{}
};

/** Indicate whether setup() has been called yet */
let ready = false;

const entry = async function (req: NextApiRequest, res: NextApiResponse): Promise<void> {
    if (!ready) {
        setup();
        ready = true;
    }

    const method = req.method?.toLowerCase();
    const path: string = "/" + ((res.params.catchall as readonly string[]) ?? []).join("/");
    const fns = method ? methodToPathToFns[method]?.[path] : undefined;
    console.log("method:", method);
    console.log("path:", path);
    console.log("fn:", fns);

    if (!fns) {
        res.status(401).send("Unknown path");
    } else if (fns.length === 0) {
        res.status(401).send("Unhandled path");
    } else {
        return new Promise((resolve, reject) => {
            let i = 0;
            const next = (err?: any) => {
                if (err) {
                    reject(err);
                } else if (i < fns.length) {
                    fns[i++](req, res, next);
                } else {
                    resolve();
                }
            };
            next();
        });
    }
}

export const GET = entry;
export const POST = entry;
export const OPTIONS = entry;

/**
 * Call the `RegisterRoutes()` function generated by tsoa.
 * `RegisterRoutes()` expects to be passed an express app, so mock the required functions (e.g. get, post, etc)
 * in order to record our own list of methods/paths/callbacks.
 */
function setup(): void {
    const app = {
        get: (path: string, ...fns: readonly FN[]) => {
            methodToPathToFns["get"][path] = fns;
        },
        delete: (path: string, ...fns: readonly FN[]) => {
            methodToPathToFns["delete"][path] = fns;
        },
        put: (path: string, ...fns: readonly FN[]) => {
            methodToPathToFns["put"][path] = fns;
        },
        post: (path: string, ...fns: readonly FN[]) => {
            methodToPathToFns["post"][path] = fns;
        },
    };
    RegisterRoutes(app as any);
    // console.log("methodToPathToFns:", methodToPathToFns);
}