apiVersion: v2
name: tokens-studio-graph-engine
maintainers:
  - name: Tokens Studio
    url: https://tokens.studio
description: The kubernetes chart for the Tokens Studio Graph Engine
keywords:
  - kubernetes
  - Tokens Studio
  - Graph Engine
sources:
  - https://github.com/penpot/penpot

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

dependencies:
  - name: onechart 
    repository: https://chart.onechart.dev
    version: 0.69.0