name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      
      - name: Install dependencies
        run: yarn --frozen-lockfile --immutable
      
      - name: Install turbo globally
        run: yarn global add turbo@1.13.3
      
      - name: Verify turbo installation
        run: turbo --version
      
      # Required for certain build and test operations
      - name: Create required directories
        run: mkdir -p .turbo graphs