name: NPM Release

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'tokens-studio/graph-engine'
    environment:
      name: prod
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn  --frozen-lockfile --prefer-offline

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.VAULT_URL }}
          role: ${{ vars.VAULT_ROLE }}
          method: jwt
          namespace: admin
          secrets: |
            ${{ vars.VAULT_PATH }} TOKEN | NPM_TOKEN;

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ steps.secrets.outputs.NPM_TOKEN }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: steps.changesets.outputs.published == 'true'
        env:
          SLACK_CHANNEL: proj-resolvers-generators
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'New version of the graph-engine has been release'
          SLACK_TITLE: "@tokens-studio/graph-engine"
          SLACK_USERNAME: "Studio Bot"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}