name: 'Codium PR Agent'

permissions:
    contents: write
    id-token: write
    pull-requests: write

on:
    pull_request:
    issue_comment:
jobs:
    pr_agent_job:
        runs-on: ubuntu-latest
        name: Run pr agent on every pull request, respond to user comments
        steps:
          - name: Import Secrets
            id: secrets
            uses: hashicorp/vault-action@v2
            with:
                url: ${{ vars.VAULT_URL }}
                role: pr-agent
                method: jwt
                namespace: admin
                secrets: |
                    secret/data/prod/services/openai token | OPENAI_KEY ;
          - name: PR Agent action step
            id: pragent
            uses: Codium-ai/pr-agent@main
            env:
                OPENAI_KEY:  ${{ steps.secrets.outputs.OPENAI_KEY }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}